//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Views.Posts {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Create_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebUI.Resources.Views.Posts.Create.ru", typeof(Create_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        internal static string TitlePlaceholder {
            get {
                return ResourceManager.GetString("TitlePlaceholder", resourceCulture);
            }
        }
        
        internal static string TitleInvalidFeedback {
            get {
                return ResourceManager.GetString("TitleInvalidFeedback", resourceCulture);
            }
        }
        
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        internal static string TopicPlaceholder {
            get {
                return ResourceManager.GetString("TopicPlaceholder", resourceCulture);
            }
        }
        
        internal static string TopicInvalidFeedback {
            get {
                return ResourceManager.GetString("TopicInvalidFeedback", resourceCulture);
            }
        }
        
        internal static string TextPlaceholder {
            get {
                return ResourceManager.GetString("TextPlaceholder", resourceCulture);
            }
        }
        
        internal static string TextInvalidFeedback {
            get {
                return ResourceManager.GetString("TextInvalidFeedback", resourceCulture);
            }
        }
        
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
    }
}
